### ISSUE TITLE
请教您一下各店铺的链接是怎么获得的？

### ISSUE THREAD

**Issue by ErazerControl** [xin-code/2019-11-11#1]
`taobao://market.m.taobao.com/app/tb-source-app/campaign/pages/index?wh_weex=true&userId=2089100916&shopId=111481369&pathInfo=/campaign-10827-88.htm#tq`
比如第一个店铺的链接是这个，如何抓取到呢？

**Comment by xin-code** [comment]
> `taobao://market.m.taobao.com/app/tb-source-app/campaign/pages/index?wh_weex=true&userId=2089100916&shopId=111481369&pathInfo=/campaign-10827-88.htm#tq`
> 比如第一个店铺的链接是这个，如何抓取到呢？
大佬，我这个是从网上找到的 只是自己用的上就放上来了 帮不上你的忙 抱歉
